# Generated by Django 5.0.7 on 2024-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gear',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Toyota', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='АИ-92', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GearBox',
        ),
        migrations.AddField(
            model_name='car',
            name='gear',
            field=models.CharField(default='Автоматическая', max_length=100),
            preserve_default=False,
        ),
    ]
