# Generated by Django 5.0.7 on 2024-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_car_brand_remove_car_fuel_remove_car_gear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электро', 'Электро'), ('Гибрид', 'Гибрид')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('Механика', 'Механика'), ('Автомат', 'Автомат'), ('Робот', 'Робот'), ('Вариатор', 'Вариатор')], max_length=100),
        ),
    ]
